# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showImage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowImage(object):
    def setupUi(self, ShowImage):
        ShowImage.setObjectName("ShowImage")
        ShowImage.resize(813, 626)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ShowImage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ShowImage)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ShowImage)
        QtCore.QMetaObject.connectSlotsByName(ShowImage)

    def retranslateUi(self, ShowImage):
        _translate = QtCore.QCoreApplication.translate
        ShowImage.setWindowTitle(_translate("ShowImage", "识别结果"))
